# Generated by Django 2.1.4 on 2019-01-07 14:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EventRules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.CharField(default='', max_length=1500)),
                ('rules', models.CharField(default='', max_length=1500)),
                ('judging', models.CharField(default='', max_length=1500)),
                ('prizes', models.CharField(default='', max_length=1500)),
                ('contacts', models.CharField(default='', max_length=1500)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.Event')),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(default='', max_length=100)),
                ('team_name', models.CharField(default='', max_length=50)),
                ('user', models.CharField(default='', max_length=100)),
                ('token', models.CharField(default='0', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event1', models.CharField(default='0', max_length=20)),
                ('event2', models.CharField(default='0', max_length=20)),
                ('event3', models.CharField(default='0', max_length=20)),
                ('event4', models.CharField(default='0', max_length=20)),
                ('event5', models.CharField(default='0', max_length=20)),
                ('event6', models.CharField(default='0', max_length=20)),
                ('event7', models.CharField(default='0', max_length=20)),
                ('event8', models.CharField(default='0', max_length=20)),
                ('event9', models.CharField(default='0', max_length=20)),
                ('event10', models.CharField(default='0', max_length=20)),
                ('event11', models.CharField(default='0', max_length=20)),
                ('event12', models.CharField(default='0', max_length=20)),
                ('event13', models.CharField(default='0', max_length=20)),
                ('event14', models.CharField(default='0', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
