# Generated by Django 2.1.4 on 2019-01-09 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_registrationmanagement_teamleader'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationmanagement',
            name='team_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='app.TeamLeader'),
        ),
    ]
