# Generated by Django 2.1.4 on 2019-01-09 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20190109_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationmanagement',
            name='team_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
