# Generated by Django 2.1.4 on 2019-01-09 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20190109_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamleader',
            name='team_leader',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
