# Generated by Django 2.1.4 on 2019-01-09 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20190109_1934'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertoken',
            old_name='event1',
            new_name='aaviskar',
        ),
        migrations.RenameField(
            model_name='usertoken',
            old_name='event10',
            new_name='auction_villa',
        ),
        migrations.RenameField(
            model_name='usertoken',
            old_name='event11',
            new_name='buffet_money',
        ),
        migrations.RenameField(
            model_name='usertoken',
            old_name='event12',
            new_name='codee',
        ),
        migrations.RenameField(
            model_name='usertoken',
            old_name='event13',
            new_name='cs_go',
        ),
        migrations.RenameField(
            model_name='usertoken',
            old_name='event2',
            new_name='guest_lecture',
        ),
        migrations.RenameField(
            model_name='usertoken',
            old_name='event3',
            new_name='lazer_maze',
        ),
        migrations.RenameField(
            model_name='usertoken',
            old_name='event4',
            new_name='marketing_roadies',
        ),
        migrations.RenameField(
            model_name='usertoken',
            old_name='event5',
            new_name='placement_fever',
        ),
        migrations.RenameField(
            model_name='usertoken',
            old_name='event6',
            new_name='pubg',
        ),
        migrations.RenameField(
            model_name='usertoken',
            old_name='event7',
            new_name='robo_soccer',
        ),
        migrations.RenameField(
            model_name='usertoken',
            old_name='event8',
            new_name='sherlocked',
        ),
        migrations.RenameField(
            model_name='usertoken',
            old_name='event9',
            new_name='technovation',
        ),
        migrations.AddField(
            model_name='usertoken',
            name='treasure_hunt',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
