# Generated by Django 2.1.4 on 2019-01-09 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20190109_2150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertoken',
            name='event14',
        ),
    ]
