# Generated by Django 2.1.4 on 2019-01-10 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_usertoken_event14'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrationmanagement',
            name='current_user',
        ),
        migrations.AddField(
            model_name='registrationmanagement',
            name='current_event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='app.Event'),
        ),
    ]
