# Generated by Django 2.1.4 on 2019-01-10 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20190110_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationmanagement',
            name='current_event',
            field=models.CharField(default='', max_length=100),
        ),
    ]
