# Generated by Django 2.1.4 on 2019-01-10 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20190110_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamleader',
            name='adm_no',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='teamleader',
            name='phone',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
