# Generated by Django 2.1.4 on 2019-01-12 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_userprofile_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_rating', models.CharField(default='', max_length=100)),
                ('number_of_rates', models.CharField(default='', max_length=100)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.Event')),
            ],
        ),
    ]
