# Generated by Django 2.1.4 on 2019-01-12 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_ratingmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratingmodel',
            name='event',
            field=models.CharField(default='', max_length=100),
        ),
    ]
