# Generated by Django 2.1.4 on 2019-01-12 15:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0018_auto_20190112_1447'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRated',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aaviskar', models.CharField(default='0', max_length=20)),
                ('technovation', models.CharField(default='0', max_length=20)),
                ('codee', models.CharField(default='0', max_length=20)),
                ('buffet_money', models.CharField(default='0', max_length=20)),
                ('robo_soccer', models.CharField(default='0', max_length=20)),
                ('lazer_maze', models.CharField(default='0', max_length=20)),
                ('placement_fever', models.CharField(default='0', max_length=20)),
                ('cs_go', models.CharField(default='0', max_length=20)),
                ('auction_villa', models.CharField(default='0', max_length=20)),
                ('treasure_hunt', models.CharField(default='0', max_length=20)),
                ('marketing_roadies', models.CharField(default='0', max_length=20)),
                ('sherlocked', models.CharField(default='0', max_length=20)),
                ('pubg', models.CharField(default='0', max_length=20)),
                ('guest_lecture', models.CharField(default='0', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
