# Generated by Django 2.1.4 on 2019-01-12 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_userrated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratingmodel',
            name='average_rating',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='ratingmodel',
            name='number_of_rates',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
