# Generated by Django 2.1.4 on 2019-01-12 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20190112_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratingmodel',
            name='average_rating',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AlterField(
            model_name='ratingmodel',
            name='event',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='ratingmodel',
            name='number_of_rates',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
