# Generated by Django 2.0.10 on 2019-01-13 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20190112_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='imageurl',
            field=models.CharField(default='', max_length=200),
        ),
    ]
