# Generated by Django 2.0.10 on 2019-01-13 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_userprofile_imageurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='imageurl',
            field=models.CharField(default='https://i.stack.imgur.com/l60Hf.png', max_length=200),
        ),
    ]
